[package]
name = "leetcode-rust"
version = "0.1.0"
authors = ["zuisong <378818573@qq.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
serde_json = "1"
tracing-subscriber = "0.3"
tracing = "0.1"
fastrand = "2"


[dev-dependencies]
test-case = "3.3.1"
base64 = { version = "0.22"}
