[package]
name = "leetcode-rust"
version = "0.1.0"
authors = ["zuisong <378818573@qq.com>"]
edition = "2018"

[dependencies]
log= "0.4.8"
chrono = "0.4.9"
failure = "0.1.6"
lazy_static = "1.4.0"
rand = "0.7.2"
env_logger = "0.7.1"

[dev-dependencies]
rstest = "0.4.1"
