[package]
name = "leetcode-rust"
version = "0.1.0"
authors = ["zuisong <378818573@qq.com>"]
edition = "2018"

[dependencies]
log= "0.4.8"
chrono = "0.4.10"
failure = "0.1.6"
lazy_static = "1.4.0"
rand = "0.7.3"
env_logger = "0.7.1"

[dev-dependencies]
test-case = "1.0.0"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
