[package]
name = "leetcode-rust"
version = "0.1.0"
authors = ["zuisong <378818573@qq.com>"]
edition = "2018"

[dependencies]
log= "0.4.8"
chrono = "0.4.11"
lazy_static = "1.4.0"
rand = "0.7.3"
simple_logger = "1.6.0"
serde_json = "1.0.52"
anyhow = "1.0.28"

[dev-dependencies]
base64 = "0.12.0"
test-case = "1.0.0"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
